apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devsecops-app-ingress
  namespace: devsecops
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - devsecops.yourdomain.com
    secretName: devsecops-tls
  rules:
  - host: devsecops.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: devsecops-app-service
            port:
              number: 80