apiVersion: v1
kind: Secret
metadata:
  name: devsecops-secrets
  namespace: devsecops
type: Opaque
data:
  # Base64 encoded values
  DB_USERNAME: ZGV2c2Vjb3BzYWRtaW4=  
  DB_PASSWORD: RGV2U2VjT3BzQDEyMw==  